import React from "react";

const Text = () => {
  const sectors = [
    { id: "1", name: "Manufacturing " },
    { id: "2", name: "Service " },
    { id: "3", name: "Other " },
    { id: "5", name: "Printing  " },
    { id: "6", name: "Food and Beverage " },
    { id: "7", name: "Textile and Clothing " },
    { id: "8", name: "Wood " },
    { id: "9", name: "Plastic and Rubber " },
    { id: "11", name: "Metalworking " },
    { id: "12", name: "Machinery " },
    { id: "13", name: "Furniture " },
    { id: "18", name: "Electronics and Optics " },
    { id: "21", name: "Transport and Logistics" },
    { id: "22", name: "Tourism " },
    { id: "19", name: "Construction materials " },
    { id: "25", name: "Business services " },
    { id: "28", name: "Information Technology and Telecommunications" },
    { id: "29", name: "Energy technology " },
    { id: "33", name: "Environment " },
    { id: "35", name: "Engineering " },
    { id: "37", name: "Creative industries " },
    { id: "39", name: "Milk &amp; dairyproducts" },
    { id: "40", name: "Meat &amp; meat products" },
    { id: "42", name: "Fish &amp; fish products" },
    { id: "43", name: "Beverages" },
    { id: "44", name: "Clothing" },
    { id: "45", name: "Textile" },
    { id: "47", name: "Wooden houses" },
    { id: "54", name: "Packaging" },
    { id: "55", name: "Blowing" },
    { id: "57", name: "Moulding" },
    { id: "53", name: "Plasticswelding and processing" },
    { id: "51", name: "Wooden buildingmaterials" },
    { id: "75", name: "CNC-machining" },
    { id: "62", name: "Forgings,Fasteners" },
    { id: "67", name: "Construction of metalstructures" },
    { id: "69", name: "Gas,Plasma, Laser cutting" },
    { id: "66", name: "MIG,TIG, Aluminum welding" },
    { id: "91", name: "Machineryequipment/tools" },
    { id: "93", name: "Metal structures" },
    { id: "94", name: "Machinery components" },
    { id: "97", name: "Maritime" },
    { id: "98", name: "Kitchen" },
    { id: "99", name: "Project furniture" },
    { id: "101", name: "Living room" },
    { id: "111", name: "Air" },
    { id: "114", name: "Rail" },
    { id: "112", name: "Road" },
    { id: "113", name: "Water" },
    { id: "121", name: "Software, Hardware" },
    { id: "122", name: "Telecommunications" },
    { id: "141", name: "Translation services " },
    { id: "145", name: "Labelling and packagingprinting" },
    { id: "148", name: "Advertising" },
    { id: "150", name: "Book/Periodicalsprinting" },
    { id: "224", name: "Manufacture of machinery" },
    { id: "227", name: "Repair and maintenanceservice" },
    { id: "230", name: "Shiprepair and conversion" },
    { id: "263", name: "Houses and buildings" },
    { id: "267", name: "Metal products" },
    { id: "269", name: "Boat/Yachtbuilding" },
    { id: "271", name: "Aluminiumand steel workboats" },
    { id: "337", name: "Other (Wood)" },
    { id: "341", name: "Outdoor" },
    { id: "342", name: "Bakery &amp;confectionery products" },
    { id: "378", name: "Sweets &amp; snack food" },
    { id: "389", name: "Bathroom/sauna" },
    { id: "385", name: "Bedroom" },
    { id: "390", name: "Children’s room" },
    { id: "392", name: "Office" },
    { id: "394", name: "Other (Furniture)" },
    { id: "437", name: "Other" },
    { id: "508", name: "Other" },
    { id: "542", name: "Metal works" },
    { id: "556", name: "Plastic goods" },
    { id: "559", name: "Plastic processingtechnology" },
    { id: "560", name: "Plastic profiles" },
    { id: "576", name: "Programming, Consultancy" },
    { id: "581", name: "Data processing, Webportals, E-marketing" },
  ];

  console.log(JSON.stringify(sectors));
  return 0;
};
export default Text;
